config/routes.rb
Rails.application.routes.draw do
  root "restaurants#index"

  resources :restaurants do
    resources :reviews, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian] }, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than: 6 }
  validates :content, presence: true
  validates :restaurant_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show]

  def index
    @restaurants = Restaurant.all
    @restaurant = Restaurant.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def show
    @review = Review.new()
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :category, :address)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]

  def new
    @review = Review.new()
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'restaurants/show', status: :unprocessable_entity
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:rating, :content, :restaurant_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Archivo:wght@200&family=Bebas+Neue&family=Familjen+Grotesk:ital,wght@1,700&family=Karla:wght@500&family=Poppins&display=swap" rel="stylesheet">
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :category, as: :select, collection: %w[chinese italian japanese french belgian] %>
  <%= f.button :submit %>
<% end %>

app/views/restaurants/index.html.erb
<h1>Yelp!</h1>

<div class="restaurants-container"
  <ul>
    <% @restaurants.each do |r| %>
      <li class="restaurant-card"><%= link_to r.name, restaurant_path(r) %></li>
    <% end %>
  </ul>
</div>

<div class="form"
  <h1>Add a new restaurant:</h1>
  <%= render "form", restaurant: @restaurant %>
</div>

app/views/restaurants/new.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :category, as: :select, collection: %w[chinese italian japanese french belgian] %>
  <%= f.button :submit %>
<% end %>

<%= link_to "<home", restaurants_path %>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %></h2>

<%= @restaurant.category %>
<%= @restaurant.address %>

<div class="reviews-container"
  <ul>
    <% @restaurant.reviews.each do |review| %>
      <li>
        <%= '⭐️' * review.rating %>
        <%= review.content %>
      </li>
    <% end %>
  </ul>
</div>

<%= render "reviews/form", restaurant: @restaurant %>

<%= link_to "<home", restaurants_path %>

app/views/reviews/_form.html.erb
<%= simple_form_for [ @restaurant, @review ] do |f| %>
  <%= f.input :rating, collection: 1..5 %>
  <%= f.input :content %>
  <%= f.button :submit %>
<% end %>